apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-readonly
  namespace: cau3
rules:
- apiGroups:
    - ""
    - "apps"
  resources:
    - "deployments"
    - "services"
  verbs:
    - "get"
    - "list"
    - "watch"
