apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: pod1
    image: busybox:1.31.1
    command: ["/bin/sh", "-c"]
    args: ["while true; do date >> /vol/date.log; sleep 5; done"]
    volumeMounts:
    - name: vol
      mountPath: /vol

  - name: pod2
    image: nginx:latest
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html

  volumes:
  - name: vol
    emptyDir: {}
